/**
 * MEDIA Guidelines
 *
 * - Keep the red thread.
 * - Keep the list sorted ascending by title.
 *
 * title:
 *   - Should not be cryptic.
 *   - Format it to Title Case.
 *   - Remove emoticons and other cosmetics.
 *   - If it's music: <artist> - <song>
 *   - If it's something else: keep it short
 *   - Put it in backticks.
 *
 * platform:
 *   - bandcamp: for media from https://bandcamp.com
 *   - soundcloud: for media from https://soundcloud.com
 *   - youtube: for media from https://youtube.com
 *
 * slug:
 *   - This is the string we need to create an embed code for the platform.
 *   - Put it in backticks.
 */
export const MEDIA: MediaListType = [
    { title: `14KT - My Heart & I`, platform: 'youtube', slug: `jrWPGEMQf5k` },
    { title: `90's Underground Hip Hop 1 (Mix)`, platform: 'youtube', slug: `PubQfGQkRpE` },
    { title: `90's Underground Hip Hop 2 (Mix)`, platform: 'youtube', slug: `rBLuvEwIF5E` },
    { title: `9th Wonder - Let Me Talk`, platform: 'youtube', slug: `nupyBT5jtTk` },
    { title: `A-Trak - DJs Gotta Dance More`, platform: 'youtube', slug: `s5GPuBjOEcA` },
    { title: `Al'tarba - Dead End`, platform: 'youtube', slug: `cnVgMf8Vze0` },
    { title: `All I Need (Blunted RnB Instrumental)`, platform: 'youtube', slug: `7Ifn-9hB3nM` },
    { title: `Andrés - Drama Around The Corner`, platform: 'youtube', slug: `En2pcUq08g4` },
    { title: `Atari Teenage Riot - Revolution Action`, platform: 'youtube', slug: `ZkivTBAMuaE` },
    { title: `Attame - 90's Hiphop Set`, platform: 'youtube', slug: `dkrpqUyiZgA` },
    { title: `Blumentopf - Irgendwie Lieb' ich das 2`, platform: 'youtube', slug: `TDE0EatumPg` },
    { title: `Boddhi Musique - For the Love of Soulful`, platform: 'youtube', slug: `ngFJlz6jJ3o` },
    { title: `BoomBaptist - King of My Castle`, platform: 'youtube', slug: `a5EGd5u6FFw` },
    { title: `BoomBaptist - Toucan Wing`, platform: 'youtube', slug: `IyYv7GP7hrk` },
    { title: `Busta Rhymes - Gimme Some More`, platform: 'youtube', slug: `un3NkWnHl9Q` },
    { title: `Cee ElAssaad - Lomhlaba (Original Mix)`, platform: 'youtube', slug: `FYhZjuj9DCk` },
    { title: `Childhood - Love Saw It`, platform: 'bandcamp', slug: `1925673495` },
    { title: `Cram - Summer Session`, platform: 'youtube', slug: `NekFeMNqvIE` },
    { title: `Daft Punk - Get Lucky (Saxophone Solo Cover)`, platform: 'youtube', slug: `3FwQzeG7hoM` },
    { title: `Dan-e-o - Dear Hip Hop`, platform: 'youtube', slug: `E7g1qKP4F3Y` },
    { title: `Demuja - Move`, platform: 'youtube', slug: `8F9n5-9Cxuw` },
    { title: `Disclosure - Ultimatum`, platform: 'youtube', slug: `F-TYRhBHbwc` },
    { title: `DJ Bailey - Intelligent Drum & Bass (Mix)`, platform: 'youtube', slug: `Yc5iPDvmEpE` },
    { title: `DJ Honda - I Need More`, platform: 'youtube', slug: `0aCRlou3unQ` },
    { title: `DJ Koze - Drone me up, Flashy feat. Sophia Kennedy (&ME Remix)`, platform: 'bandcamp', slug: `4131922422` },
    { title: `DJ Shadow - Urgent, Important, Please Read`, platform: 'youtube', slug: `l8OE8kg7DoQ` },
    { title: `DNS - 5lack`, platform: 'youtube', slug: `L1iL9oAKN9E` },
    { title: `Draw4 - Kanjou Mid Night`, platform: 'youtube', slug: `tsmROPY_zF0` },
    { title: `Elvis Presley - A Little Less Conversation`, platform: 'youtube', slug: `sNUSBi8x4tg` },
    { title: `Eminem - It's OK`, platform: 'youtube', slug: `1wMPQ99nBwQ` },
    { title: `Endless Summer (Blunted HipHop Instrumental)`, platform: 'youtube', slug: `JN7afZnny-o` },
    { title: `Extra Produktionen - The Mothership`, platform: 'youtube', slug: `nZ5kwd3-Tr0` },
    { title: `Fernanda Pistelli Live @ Universo Paralello Festival 2020`, platform: 'youtube', slug: `4ImCuGValoo` },
    { title: `Fonki Cheff - 90s Classic Hip Hop (Mix)`, platform: 'youtube', slug: `rHlltz3xhGI` },
    { title: `Funky Notes - Never Knew`, platform: 'youtube', slug: `AauqU7Rm8Xg` },
    { title: `Gabriel Garzón-Montano - Everything Is Everything`, platform: 'youtube', slug: `Z2WH42MLgUE` },
    { title: `Gabriel Garzón-Montano - Golden Wings`, platform: 'youtube', slug: `l4LFawdddFE` },
    { title: `Gift of Gab - The Ride of your Life`, platform: 'youtube', slug: `RFE66SEwo7Y` },
    { title: `Hanna - Sometimes (Karol XVII & MB Valence Remix)`, platform: 'youtube', slug: `INxh_eCFEpo` },
    { title: `High in the Sky (Blunted HipHop Beat)`, platform: 'youtube', slug: `0mpcC_8YQ5g` },
    { title: `Hip Hop 1995 (Mix)`, platform: 'youtube', slug: `S66-QsQJg8I` },
    { title: `Intelligent Drum & Bass - Selected Works (1994-2000)`, platform: 'youtube', slug: `1zGaTE2AmsU` },
    { title: `Jamal - Keep It Real`, platform: 'youtube', slug: `_gmmvFBGkjc` },
    { title: `Jeff Mills, Jean-Phi Dary & Prabhu Edouard - Tomorrow Comes The Harvest`, platform: 'youtube', slug: `EahXXV0KlCY` },
    { title: `Johannes Heil - Die Zahl des Tieres`, platform: 'youtube', slug: `F1O8tBPZecA` },
    { title: `Juma - Show me`, platform: 'youtube', slug: `kYk7G-_wqzQ` },
    { title: `Katarakt - LoFi House (Mix)`, platform: 'youtube', slug: `mlUMgZGFCtw` },
    { title: `Kendrick Lamar - How Much A Dollar Cost`, platform: 'youtube', slug: `y8kEiL81_R4` },
    { title: `King Gizzard & The Lizard Wizard - Black Hot Soup (DJ Shadow "My Own Reality" Re-Write)`, platform: 'youtube', slug: `MJkbQLVeFPs` },
    { title: `Kobacchi Ryo - Bilal`, platform: 'youtube', slug: `ulTuqFamxPQ` },
    { title: `Krazy - Riddle`, platform: 'youtube', slug: `TvPupGl4m7M` },
    { title: `KRS-One - Don't Fall For It`, platform: 'youtube', slug: `efMiGjf_bic` },
    { title: `KRS-One - Raw Hip Hop`, platform: 'youtube', slug: `cDw8U32IqUc` },
    { title: `L'indécis - Soulful (Chillhop Live Session)`, platform: 'youtube', slug: `-NxV_nqD1N0` },
    { title: `Lamb - Trans Fatty Acid (Kruder & Dorfmeister Session Mix)`, platform: 'youtube', slug: `94NU-W-KgxI` },
    { title: `Legend Of 1900 - Piano Duel Enduring Movement`, platform: 'youtube', slug: `ETZJo4TcbQk` },
    { title: `Lochive The DJ - Deep and Soulful House (Mix)`, platform: 'youtube', slug: `dxfWIa8PQ0w` },
    { title: `LSB - Overthinking`, platform: 'youtube', slug: `-4Cm90l5egE` },
    { title: `Masayasu Tzboguchi Trio - Bleu Arbre`, platform: 'youtube', slug: `N8no77e-52g` },
    { title: `Massive Töne - Das und Dies (Remix)`, platform: 'youtube', slug: `rQtChq8GARw` },
    { title: `Michael Jackson - Don't Stop 'Til You Get Enough`, platform: 'youtube', slug: `yURRmWtbTbo` },
    { title: `Michael Jackson - Leave Me Alone`, platform: 'youtube', slug: `crbFmpezO4A` },
    { title: `Michel Cleis - La Mezcla (Paul Kalkbrenner Remix)`, platform: 'youtube', slug: `jt593vq7_rY` },
    { title: `Mid 90'S Intelligent Drum & Bass (Mix)`, platform: 'youtube', slug: `R_XlJfWakfA` },
    { title: `Modjo - Lady (Hear Me Tonight)`, platform: 'youtube', slug: `vRB1MLGEHSc` },
    { title: `Mononome - Hands Of Time`, platform: 'youtube', slug: `gRPd5oWTL2M` },
    { title: `Moods - Distance`, platform: 'youtube', slug: `aB1mpk78pVE` },
    { title: `Moods - Rain Showers`, platform: 'youtube', slug: `Qb9Fgf1mjgk` },
    { title: `More Ghost Than Man - The Courage To Lie To A Dying Man`, platform: 'youtube', slug: `uuxSO85By2Q` },
    { title: `Mr. Schnabel - Hi, bin Howard`, platform: 'youtube', slug: `DYpaNTIP6QE` },
    { title: `Newen Afrobeat - Opposite People`, platform: 'youtube', slug: `mFSRCG4DrmI` },
    { title: `Niah - Bets`, platform: 'youtube', slug: `Qfdh-1AplSk` },
    { title: `Nutty Nys - The Promise`, platform: 'bandcamp', slug: `749774213` },
    { title: `Oldy Clap Recordz - Bloqué En 90`, platform: 'youtube', slug: `gp7m0WvmRBI` },
    { title: `Oteck instrumental - Crazy beat`, platform: 'youtube', slug: `RWMK9vS1N00` },
    { title: `Outkast - Ms. Jackson`, platform: 'youtube', slug: `MYxAiK6VnXw` },
    { title: `Pad Chennington - Vaporwave & Future Funk & House DJ Mix`, platform: 'youtube', slug: `iBwohlOvzHc` },
    { title: `Peshay Studio Set (Mix)`, platform: 'youtube', slug: `JK8ilaPZbKE` },
    { title: `Pharoahe Monch - F*** You`, platform: 'youtube', slug: `4FqbkKh8mro` },
    { title: `Prefuse 73 - Nuno`, platform: 'youtube', slug: `DYWAcmslvvo` },
    { title: `Pushin On High (Oldschool HipHop Instrumental)`, platform: 'youtube', slug: `oOW9DfiGAn4` },
    { title: `Robert Glasper - So Beautiful (Live)`, platform: 'youtube', slug: `GS2Y_CkaXP0` },
    { title: `Roger Sanchez - Another Chance`, platform: 'youtube', slug: `rdlvPe959Ck` },
    { title: `Ryuzo - The Story`, platform: 'youtube', slug: `8A2f6fYbcu0` },
    { title: `Shia LaBeouf - Just Do It`, platform: 'youtube', slug: `ZXsQAXx_ao0` },
    { title: `Snoop Dogg - Gin & Juice`, platform: 'youtube', slug: `DI3yXg-sX5c` },
    { title: `Soho - Hot Music`, platform: 'youtube', slug: `p30DUmx9v3Q` },
    { title: `Solo For Dolo - Ain't No Love`, platform: 'bandcamp', slug: `3707273849` },
    { title: `SPARTALIEN & Esblendet - Rainbows & Unicorns`, platform: 'soundcloud', slug: `922777060` },
    { title: `The Four Owls - Old Earth`, platform: 'bandcamp', slug: `3801938764` },
    { title: `The Horrorist - One Night In New York City`, platform: 'youtube', slug: `oVgjC5Gw8y0` },
    { title: `The Smashing Pumpkins - 1979`, platform: 'youtube', slug: `4aeETEoNfOg` },
    { title: `Tom Middleton - Shinkansen`, platform: 'youtube', slug: `CU2rg6aeKh0` },
    { title: `Tool - Bottom (Live In Oakland, CA - 12-31-'95)`, platform: 'youtube', slug: `Cy2qIulPiMA` },
    { title: `Torch - Kapitel 29`, platform: 'youtube', slug: `w97E3FoCiXw` },
    { title: `Torch - Morgen`, platform: 'youtube', slug: `x8eVPRp483E` },
    { title: `Trans-Central Connection (Mix)`, platform: 'youtube', slug: `rz3JVZbmoCg` },
    { title: `Tribal Jam - 925`, platform: 'youtube', slug: `hZZa7Z1oG38` },
    { title: `Trife Life (Oldschool HipHop Instrumental)`, platform: 'youtube', slug: `VhtNsMx66lE` },
    { title: `U_Know (Olive Oil x Miles Word) - In A Row`, platform: 'youtube', slug: `Z8utqVZ5J7I` },
    { title: `Ugly Heroes - Today Right Now`, platform: 'bandcamp', slug: `2939601556` },
    { title: `Verbz & Mr Slipz - For My Peeps`, platform: 'youtube', slug: `nzy7JHyr4B8` },
    { title: `Vinnie Paz - Beautiful Love`, platform: 'youtube', slug: `-AxfryuyLQg` },
    { title: `Vy Pole - V`, platform: 'youtube', slug: `rzCCahBMwrk` },
    { title: `Wamdue Project - King of My Castle`, platform: 'youtube', slug: `DXSyQjppqG0` },
    { title: `Womack & Womack - Teardrops`, platform: 'youtube', slug: `R8AOAap6_k4` },
]
